(scorecard): Add new images for default untar and storage options (#6335)
* add images for scorecard untar and storage

Signed-off-by: Bryce Palmer <bpalmer@redhat.com>

* Add new images for scorecard

and use them as the default untar and storage images to ensure
that scorecard pods are fully compliant with restricted PSA. This
is done by making the images run as non-root by default (sets the user
to non-root in the Dockerfile)

fixes #6295

Signed-off-by: Bryce Palmer <bpalmer@redhat.com>

* update images & docs;add changelog

Signed-off-by: Bryce Palmer <bpalmer@redhat.com>

* add missing newline

Signed-off-by: Bryce Palmer <bpalmer@redhat.com>

---------

Signed-off-by: Bryce Palmer <bpalmer@redhat.com>

diff --git a/.github/workflows/deploy-manual.yml b/.github/workflows/deploy-manual.yml
--- a/.github/workflows/deploy-manual.yml
+++ b/.github/workflows/deploy-manual.yml
@@ -17,6 +17,13 @@ jobs:
     environment: deploy
     steps:
 
+    # https://github.com/orgs/community/discussions/47863
+    - name: update packages
+      run: |
+        sudo apt-mark hold grub-efi-amd64-signed
+        sudo apt-get update --fix-missing
+        sudo apt upgrade -y
+
     - name: set up qemu
       uses: docker/setup-qemu-action@v2
 
@@ -48,7 +55,7 @@ jobs:
         fi
         echo "tag=${IMG}:${TAG}" >> $GITHUB_OUTPUT
         echo "git_commit=${GIT_COMMIT}" >> $GITHUB_OUTPUT
-    
+
     - name: create 2.11-base tag
       id: base_tag_211
       run: |
@@ -67,65 +74,65 @@ jobs:
       with:
         file: ./images/ansible-operator/base.Dockerfile
         context: ./images/ansible-operator
-        platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
+        platforms: linux/s390x
         push: true
         tags: ${{ steps.base_tag_29.outputs.tag }}
         build-args: |
           GIT_COMMIT=${{ steps.base_tag_29.outputs.git_commit }}
 
-    - name: build and push ansible 2.11 dep image
-      uses: docker/build-push-action@v3
-      with:
-        file: ./images/ansible-operator-2.11-preview/base.Dockerfile
-        context: ./images/ansible-operator-2.11-preview
-        platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
-        push: true
-        tags: ${{ steps.base_tag_211.outputs.tag }}
-        build-args: |
-          GIT_COMMIT=${{ steps.base_tag_211.outputs.git_commit }}
+    # - name: build and push ansible 2.11 dep image
+    #   uses: docker/build-push-action@v3
+    #   with:
+    #     file: ./images/ansible-operator-2.11-preview/base.Dockerfile
+    #     context: ./images/ansible-operator-2.11-preview
+    #     platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
+    #     push: true
+    #     tags: ${{ steps.base_tag_211.outputs.tag }}
+    #     build-args: |
+    #       GIT_COMMIT=${{ steps.base_tag_211.outputs.git_commit }}
 
-    # This change will be staged and committed in the PR pushed below.
-    # The script below will fail if no change was made.
-    - name: update base of ansible-operator 2.9
-      id: update_29
-      run: |
-        set -ex
-        sed -i -E 's|FROM quay\.io/operator-framework/ansible-operator-base:.+|FROM ${{ steps.base_tag_29.outputs.tag }}|g' images/ansible-operator/Dockerfile
-        git diff --exit-code --quiet && echo "Failed to update images/ansible-operator/Dockerfile" && exit 1
-        REF="${{ github.event.ref }}"
-        echo "branch_name=${REF##*/}" >> $GITHUB_OUTPUT
+    # # This change will be staged and committed in the PR pushed below.
+    # # The script below will fail if no change was made.
+    # - name: update base of ansible-operator 2.9
+    #   id: update_29
+    #   run: |
+    #     set -ex
+    #     sed -i -E 's|FROM quay\.io/operator-framework/ansible-operator-base:.+|FROM ${{ steps.base_tag_29.outputs.tag }}|g' images/ansible-operator/Dockerfile
+    #     git diff --exit-code --quiet && echo "Failed to update images/ansible-operator/Dockerfile" && exit 1
+    #     REF="${{ github.event.ref }}"
+    #     echo "branch_name=${REF##*/}" >> $GITHUB_OUTPUT
 
-    - name: create PR for ansible-operator 2.9 Dockerfile
-      uses: peter-evans/create-pull-request@v3
-      with:
-        title: "[${{ steps.update_29.outputs.branch_name }}] image(ansible-operator): bump base to ${{ steps.base_tag_29.outputs.tag }}"
-        commit-message: |
-          [${{ steps.update_29.outputs.branch_name }}] image(ansible-operator): bump base to ${{ steps.base_tag_29.outputs.tag }}
+    # - name: create PR for ansible-operator 2.9 Dockerfile
+    #   uses: peter-evans/create-pull-request@v3
+    #   with:
+    #     title: "[${{ steps.update_29.outputs.branch_name }}] image(ansible-operator): bump base to ${{ steps.base_tag_29.outputs.tag }}"
+    #     commit-message: |
+    #       [${{ steps.update_29.outputs.branch_name }}] image(ansible-operator): bump base to ${{ steps.base_tag_29.outputs.tag }}
 
-          Signed-off-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
-        body: "New ansible-operator-base image built by https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-        delete-branch: true
-        branch-suffix: short-commit-hash
+    #       Signed-off-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
+    #     body: "New ansible-operator-base image built by https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+    #     delete-branch: true
+    #     branch-suffix: short-commit-hash
 
-    # This change will be staged and committed in the PR pushed below.
-    # The script below will fail if no change was made.
-    - name: update base of ansible-operator-2.11-preview
-      id: update_211
-      run: |
-        set -ex
-        sed -i -E 's|FROM quay\.io/operator-framework/ansible-operator-2.11-preview-base:.+|FROM ${{ steps.base_tag_211.outputs.tag }}|g' images/ansible-operator-2.11-preview/Dockerfile
-        git diff --exit-code --quiet && echo "Failed to update images/ansible-operator-11-preview-base/Dockerfile" && exit 1
-        REF="${{ github.event.ref }}"
-        echo "branch_name=${REF##*/}" >> $GITHUB_OUTPUT
+    # # This change will be staged and committed in the PR pushed below.
+    # # The script below will fail if no change was made.
+    # - name: update base of ansible-operator-2.11-preview
+    #   id: update_211
+    #   run: |
+    #     set -ex
+    #     sed -i -E 's|FROM quay\.io/operator-framework/ansible-operator-2.11-preview-base:.+|FROM ${{ steps.base_tag_211.outputs.tag }}|g' images/ansible-operator-2.11-preview/Dockerfile
+    #     git diff --exit-code --quiet && echo "Failed to update images/ansible-operator-11-preview-base/Dockerfile" && exit 1
+    #     REF="${{ github.event.ref }}"
+    #     echo "branch_name=${REF##*/}" >> $GITHUB_OUTPUT
 
-    - name: create PR for ansible-operator-2.11-preview Dockerfile
-      uses: peter-evans/create-pull-request@v3
-      with:
-        title: "[${{ steps.update_211.outputs.branch_name }}] image(ansible-operator-2.11-preview): bump base to ${{ steps.base_tag_211.outputs.tag }}"
-        commit-message: |
-          [${{ steps.update_211.outputs.branch_name }}] image(ansible-operator-2.11-preview): bump base to ${{ steps.base_tag_211.outputs.tag }}
+    # - name: create PR for ansible-operator-2.11-preview Dockerfile
+    #   uses: peter-evans/create-pull-request@v3
+    #   with:
+    #     title: "[${{ steps.update_211.outputs.branch_name }}] image(ansible-operator-2.11-preview): bump base to ${{ steps.base_tag_211.outputs.tag }}"
+    #     commit-message: |
+    #       [${{ steps.update_211.outputs.branch_name }}] image(ansible-operator-2.11-preview): bump base to ${{ steps.base_tag_211.outputs.tag }}
 
-          Signed-off-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
-        body: "New ansible-operator-2.11-preview-base image built by https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
-        delete-branch: true
-        branch-suffix: short-commit-hash
+    #       Signed-off-by: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
+    #     body: "New ansible-operator-2.11-preview-base image built by https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+    #     delete-branch: true
+    #     branch-suffix: short-commit-hash
